# Generated by Django 5.2.7 on 2025-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('Pasta', 'Pasta'), ('Ensalada', 'Ensalada'), ('Postre', 'Postre'), ('Plato Principal', 'Plato Principal'), ('Desayuno', 'Desayuno'), ('Vegetariana', 'Vegetariana')], default='Plato Principal', max_length=50),
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(blank=True, help_text='Número de personas para las que rinde la receta', null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.CharField(blank=True, help_text="Ej: '30 min', '1 hora'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(default='recetas_pics/default.png', upload_to='recetas_pics/'),
        ),
    ]
