# Generated by Django 5.2.7 on 2025-10-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_categoria_receta_porciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIO', 'Medio'), ('DIFICIL', 'Difícil')], default='FACIL', help_text='Nivel de complejidad de la receta.', max_length=10),
        ),
    ]
